apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubia
spec:
  rules:
  - host: kubia.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend-service
          servicePort: 8080
      - path: /backend
        backend:
          serviceName: backend-service
          servicePort: 18080
