apiVersion: v1
kind: Service
metadata:
  name: k8s-learn
  labels:
    app: k8s-learn
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: tcp
    targetPort: 8080
  selector:
    app: frontend
